  # This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require_relative 'fastfile_helpers.rb'

default_platform(:android)

platform :android do

  desc "Increment version code"
  lane :increment_vc do
  increment_version_code(
       gradle_file_path: "./app/build.gradle",
  )
  end

  # Use fastlane appcenter_upload_sim_app env:dev to upload 'dev' version of the app to app_center 
  # Use fastlane appcenter_upload_sim_app env:stg to upload 'stg' version of the app to the app_center 
  # requires plugin -> fastlane add_plugin appcenter
  desc "Upload the app to app center"
  lane :appcenter_upload_app do | options | 
    appcenter_upload(
      api_token: ENV["APPCENTER_API_KEY"],
      owner_name: "Unfinished",
      app_name: "standalone-wallet-" + options[:"env"],
      version: options[:"build_version"], #TODO needs to be 
      file: project_path + "/app/build/outputs/apk/debug/app-debug.apk"
    )
  end

end