name: Build & Upload

on:
  push:
    branches: [ feature/github-action-build-apk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      # Cache gradle
      - name: Cache Gradle and Wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: cache-${{ runner.os }}-${{ matrix.jdk }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Build Debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload Build Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Post to a Slack channel
          id: slack
          uses: slackapi/slack-github-action@v1.18.0

          with:
            channel-id: 'android-release'
            slack-message: "Test message"
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN_ONLY_WRITE_PERMISSION }}